# Generated by Django 4.0.3 on 2022-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date_published', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('prep_time', models.CharField(blank=True, max_length=32)),
                ('cook_time', models.CharField(blank=True, max_length=32)),
                ('total_time', models.CharField(blank=True, max_length=32)),
                ('servings', models.IntegerField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('url_hash', models.BigIntegerField(db_index=True)),
            ],
        ),
    ]
