# Generated by Django 4.0.3 on 2022-03-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_alter_recipe_cook_time_alter_recipe_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
