# Generated by Django 4.0.3 on 2022-03-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_alter_recipe_servings'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_hash', models.BigIntegerField(db_index=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='url_hash',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.visitedurl'),
        ),
    ]
