# Generated by Django 4.0.3 on 2022-03-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_visitedurl_remove_recipe_url_hash_alter_recipe_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipies.visitedurl'),
        ),
    ]
