# Generated by Django 4.0.3 on 2022-03-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0006_author_image_recipe_author_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
