# Generated by Django 4.0.3 on 2022-03-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_rating_recipe_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='keywords',
            field=models.ManyToManyField(to='recipies.keyword'),
        ),
    ]
