# Generated by Django 4.0.3 on 2022-03-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0009_keyword_recipe_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='keywords',
            field=models.ManyToManyField(related_name='recipies', to='recipies.keyword'),
        ),
    ]
