# Generated by Django 4.0.3 on 2022-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0010_alter_recipe_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
